config/routes.rb
Rails.application.routes.draw do
  get 'webservice/temperatura'
  get 'webservice' => 'webservice#index'

end

app/models/webservice.rb
class Webservice

def index()


end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/webservice_controller.rb
require 'net/http'
  
require 'rexml/document'

class WebserviceController < ApplicationController

	def index
	end

	def temperatura()

		city_name = URI.escape(params[:city_name])
		country_name = URI.escape(params[:country_name])

		url = "http://www.webservicex.net/globalweather.asmx/GetWeather?CityName=#{city_name}&CountryName=#{country_name}"
		resp = Net::HTTP.get_response(URI.parse(url)).body # get_response takes an URI object

		@doc = REXML::Document.new(resp)

		@teste = Hash.from_xml(@doc.root.get_text.value)


	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/webservice_helper.rb
module WebserviceHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Condiçoes Climáticas</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/webservice/index.html.erb
<%= form_tag webservice_temperatura_path, method: :get do  %>
  Cidade: <%= text_field_tag :city_name %><br />
  Pais : <%= text_field_tag :country_name %><br />
  <%= submit_tag 'Ver temperatura' %>
<% end %>

app/views/webservice/temperatura.html.erb
<h1>Temperatura</h1>

<% if @teste['CurrentWeather'] %>
	<% @teste['CurrentWeather'].each do |key, value| %>
		<%= key %>: <b><%= value %></b>
		<br>	
	<% end %>
<% end %>